//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мастерская1
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Каталог
    {
        public int id { get; set; }
        public string Название { get; set; }
        public decimal Цена { get; set; }
        public string Фото { get; set; }

        public string ImgPath
        {
            get
            {
                if (File.Exists(Directory.GetCurrentDirectory() + @"\Resources\" + this.Название + ".jpg"))
                {
                    return "/Resources/" + this.Название + ".jpg";
                }
                else
                {
                    return "/Resources/picture.png";
                }
            }
        }
    }
}
